#pragma once

constexpr std::u8string_view defConfigFile = u8""
"style: &style\r\n"
"# Remove '#' to override font style\r\n"
"#  size: 0\r\n"
"#  width: 0\r\n"
"#  weight: 0\r\n"
"#  italic: false\r\n"
"#  underLine: false\r\n"
"#  strikeOut: false\r\n"
"#  charSet: 0\r\n"
"#  outPrecision: 0\r\n"
"#  clipPrecision: 0\r\n"
"#  quality: 0\r\n"
"#  pitchAndFamily: 0\r\n"
"\r\n"
"fonts:\r\n"
"  SimSun: &zh-cn-font # Chinese (Simplified) fallback font\r\n"
"    replace: Microsoft YaHei\r\n"
"    <<: *style\r\n"
"  PMingLiU: # Chinese (Traditional) fallback font\r\n"
"    replace: Microsoft JhengHei UI\r\n"
"    <<: *style\r\n"
"  MS UI Gothic: # Japanese fallback font\r\n"
"    replace: Yu Gothic UI\r\n"
"    <<: *style\r\n"
"  Gulim: # Korean fallback font\r\n"
"    replace: 맑은 고딕\r\n"
"    <<: *style\r\n"
"\r\n"
"#fixGSOFont: true # true is to use system UI font\r\n"
"#fixGSOFont: *zh-cn-font # Or replace with user defined font\r\n"
"\r\n"
"#gdiplus:\r\n"
"#  SimSun:\r\n"
"#    replace: Microsoft YaHei\r\n"
"#  Microsoft YaHei:\r\n"
"#    size: 72.0\r\n"
"#    style: regular\r\n"
"##    style: 0\r\n"
"#    unit: point\r\n"
"##    unit: 3\r\n"
"\r\n"
"#gdipGFFSansSerif: Calibri\r\n"
"#gdipGFFSerif: Times New Roman\r\n"
"#gdipGFFMonospace: Consolas\r\n"
"\r\n"
"debug: false\r\n";
